[package]
name = "logistic_regression"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion" }
starknet = ">=2.1.0"
# foo = { path = "vendor/foo" }


[[target.starknet-contract]]
sierra = true

# Enable CASM codegen.
casm = false
# Emit Python-powered hints in order to run compiled CASM class with legacy Cairo VM.
casm-add-pythonic-hints = false

allowed-libfuncs = false
